#FONDO DE PANTALLA
SRPITE_FONDO_PANTALLA = "./assets/Imagenes/fondo.gif"

#TAMAÑO PANTALLA
TAM_PANTALLA_X = 500
TAM_PANTALLA_Y = 500

#CONSTANTE FUENTE DE MENU
FUENTE_MENU_FONT = None
FUENTE_MENU_TAMAÑO = 36
FUENTE_MENU_COLOR = (255, 255, 255)
FUENTE_MENU_COLOR_SELECCION = (255, 255, 0)

#CONSTANTES JUGADOR
PUNTUACION_INICIAL_JUGADOR = 0
VIDAS_INICIALES_JUGADOR = 3
BANDERAS_INICIALES_JUGADOR = 0

TAM_NAV_JUGADOR_X = 50
TAM_NAV_JUGADOR_Y = 50
VELOCIDAD_NAV_JUGADOR = 5
IMG_NAVE_JUGADOR = "./assets/Imagenes/5.png"

#CONSTANTES BALA
COLOR_SPRITE_BALA = (255, 0, 0) 
TAM_SPRITE_BALA = 3
VELOCIDAD_SPRITE_BALA = 10

