#TAMAÑO PANTALLA
TAM_PANTALLA_X = 500
TAM_PANTALLA_Y = 500


#CONSTANTES JUGADOR
PUNTUACION_INICIAL_JUGADOR = 0
VIDAS_INICIALES_JUGADOR = 3
BANDERAS_INICIALES_JUGADOR = 0

#CONSTANTES BALA
TAMAÑO_BALA = (8, 16)
VELOCIDAD_BALA = 8
IMG_BALA = "./assets/Imagenes/bala.png"

